version: '3.9'

services:
        db:
          image: mongo
          container_name: db
          restart: always
          enviroment: 
              - MONGO_INTIDB_ROOT_USERNAME=dio
              - MONGO_INITDB_ROOT_PASSWORD=dio
          ports: 
            - "27017:27017"
          volumes:
            - C:/Users/vinic/Documents/Dev/Estudos/BootcampEduzz/MongoDB/dbdata:/dbdata/db